### ISSUE TITLE
User attribute default_value wildcard 500 error

### ISSUE THREAD

**Issue by BrianDMG** [hirosassa/terraform-provider-looker#18]
Using v0.8.2, when trying to use a wildcard as the default value in a user_attribute of advanced_filter_string type, the server returns a 500 error. This error only seems to show up on newly-created objects, but will apply to existing user_attribute objects with no problem. 

This value (`"%, NULL"`) is being used as described in the official Looker documentation ([here](https://docs.looker.com/admin-options/settings/user-attributes#creating_user_attributes)) under the **Assigning values to individual users** header.

Failure conditions:

- user_attribute object does not already exist
- % is used in the default_value field

Sample code:
```
resource "looker_user_attribute" "some_user_attribute" {
  name            = "some_user_attribute"
  label           = "Example user_attribute"
  type            = "advanced_filter_string"
  user_can_view   = true
  user_can_edit   = false
  value_is_hidden = false
  default_value   = "%, NULL"
}
```

Error in pipeline: `Error: response error: 500 Internal Server Error`

Error in Looker log:
```
{"msg":"Rack app error: #<Rack::QueryParser::InvalidParameterError: invalid %-encoding (
  {\"name\":\"some_user_attribute\",
    \"label\":\"Example user_attribute\",
    \"type\":\"advanced_filter_string\",
    \"default_value\":\"%, NULL\",
    \"value_is_hidden\":false,
    \"user_can_view\":true,
    \"user_can_edi\":false})>",
    "h":"pod.ip.address",
    "n":"some_org",
    "nid":24,
    "t":"2022-03-11T15:20:38.639+00:00",
    "s":"ERROR",
    "rid":"4c2b6",
    "c":"puma"
  }
)}
```

**Comment by hirosassa** [comment]
@BrianDMG Hi, Brian. Thank you for reporting the issue! I'll take a look.

**Comment by hirosassa** [comment]
@BrianDMG Thanks again for your contribution of #24. 
I happy to create PR in this weekend or can you make PR for this?

**Comment by BrianDMG** [comment]
I would love to, but I'm honestly not sure what's causing this issue. It might be something on the Looker API side.

**Comment by hirosassa** [comment]
OK! So, I'll try in this weekend!

**Comment by hirosassa** [comment]
@BrianDMG I found the bug in SDK and create a issue on the repo. Please wait a moment 🙇 

https://github.com/looker-open-source/sdk-codegen/issues/1075
