### ISSUE TITLE
v0.8.4 - Error: user_attribute_id: '' expected type 'int', got unconvertible type 'string', value: '22'

### ISSUE THREAD

**Issue by BrianDMG** [hirosassa/terraform-provider-looker#23]
When trying to create a user_attribute_group_value object, I get the following error:

```Error: user_attribute_id: '' expected type 'int', got unconvertible type 'string', value: '22'
│ 
│   with module.looker.looker_user_attribute_group_value.some_group_value_object,
│   on modules/looker/user_attribute_group_value.tf line 64, in resource "looker_user_attribute_group_value" "some_group_value_object":
│   64: resource "looker_user_attribute_group_value" "some_group_value_object" {
```

The group_id in question is from a group that is also defined in Terraform, so I am just using `looker_user_attribute.some_user_attribute.id` to reference it in the user attribute group value object. I have also tried using tonumber() to force it to show up as an int, and get the same error. 22 is the correct ID for the object referenced in the error.

**Comment by hirosassa** [comment]
@BrianDMG Oh, this might be my fault of recent release. I'll fix and release immediately. Thanks for your report.

**Comment by BrianDMG** [comment]
I was just about to start the process of submitting a PR, but if you can knock it out easier, that's great. Thanks for all your ongoing work on this, btw!

**Comment by hirosassa** [comment]
@BrianDMG 
> I was just about to start the process of submitting a PR

Oh, sounds great! Please go ahead! I'll review soon.
