### ISSUE TITLE
Issue creating looker_connections

### ISSUE THREAD

**Issue by IkePCampbell** [hirosassa/terraform-provider-looker#29]
Using 0.8.5 and with the code

```
resource "looker_connection" "database_connections" {
  name                         = "test_postgres"
  dialect_name                 = "postgres"
  host                         = var.host
  port                         = 5555
  username                     =  "foo"
  password                     = "bar"
  database                     = "my_db"
  ssl                          = true
}
```

I get 
```Error: response error. status=500 Internal Server Error. error={"message":"An error has occurred.","documentation_url":"https://docs.looker.com/"}```

**Comment by hirosassa** [comment]
Thank your for your suggestion. I'm currently very busy on my work, but I'll take a look shortly (maybe this weekend).

**Comment by IkePCampbell** [comment]
Thank yewwwww

**Comment by hirosassa** [comment]
@IkePCampbell Thanks for your report! I'll close this issue.
