### ISSUE TITLE
Change to connection certificate does not trigger resource update

### ISSUE THREAD

**Issue by dave-pollock** [hirosassa/terraform-provider-looker#39]
Given this setup:
```
resource "google_service_account" "looker" {
  account_id = "looker"
  display_name = "looker"
}

resource "google_service_account_key" "looker" {
  service_account_id = google_service_account.looker.name
}

resource "looker_connection" "bigquery_connection" {
  name = "some_connection"
  host = "some_project_id"
  username = google_service_account.looker.email
  certificate = google_service_account_key.looker.private_key
  file_type = ".json"
  database = "some_database"
  dialect_name = "bigquery_standard_sql"
}
```

If the `google_service_account_key` resource is replaced, it does not trigger the `certificate` field in the `looker_connection` to be updated.

I assume this is due to this suppression function? https://github.com/hirosassa/terraform-provider-looker/blob/master/pkg/looker/resource_connection.go#L59-L61

It would be useful if changes to the `certificate` triggered the `looker_connection` resource to be updated. I often need to rotate keys and having the connection automatically updated would be very helpful.

**Comment by hirosassa** [comment]
@dave-pollock Thanks for your information! Your suggestion looks right.
If you want to create the PR for this, I would like to review. 
Or, of course,  it is OK that I can create it.

**Comment by dave-pollock** [comment]
@hirosassa I've had a go at it: https://github.com/hirosassa/terraform-provider-looker/pull/40
