### ISSUE TITLE
Found typo in code, terraform-provider-looker/pkg/looker/resource_connection.go

### ISSUE THREAD

**Issue by nut1204** [hirosassa/terraform-provider-looker#46]
I found a typo in the code on line 176. The word 'passowrd' should be 'password'. This is maybe causing the code to produce unexpected results.

https://github.com/hirosassa/terraform-provider-looker/blob/89a1ec42026600176be2843b77727b352030e327/pkg/looker/resource_connection.go#L176

https://github.com/hirosassa/terraform-provider-looker/blob/89a1ec42026600176be2843b77727b352030e327/pkg/looker/resource_connection.go#L436

![image](https://user-images.githubusercontent.com/1725399/221893896-7a17d5d1-336e-4317-9d77-0e802dd14f03.png)

**Comment by hirosassa** [comment]
@nut1204 Thank you for writing in! Cloud you create a PR to solve this? or I can go, too.

**Comment by hirosassa** [comment]
@nut1204 I'm sorry for keeping you waiting so long.
This bug is fixed in @jbennett77 's contribution.
cc @jbennett77
https://github.com/hirosassa/terraform-provider-looker/pull/48
